version: "3.8"

services:
  app:
    image: node:14-alpine
    environment:
      PORT: 3000
    container_name: node-app
    volumes:
      - $PWD:/app
    working_dir: /app
    command:
      - npm
      - start
    ports:
      - 3000:3000
